# Generated by Django 5.0.2 on 2024-03-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ReferredDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_owed', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front_desk.patient')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_desk.referreddoctor')),
                ('requisitions', models.ManyToManyField(to='front_desk.service')),
            ],
        ),
    ]
